apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "places-backend.fullname" . }}
  labels:
    {{- include "places-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "places-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "places-backend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "pcasselacr.azurecr.io/locations-backend:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
