apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "places-backend.fullname" . }}
  labels:
    {{- include "places-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "places-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "places-backend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "pcasselacr.azurecr.io/locations-backend:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: RUST_LOG
              value: debug
            - name: POSTGRES_HOST
              value: places-db.postgres.database.azure.com
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESUSER
            - name: POSTGRES_DATABASE
              value: prod
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRESPASSWORD
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "places-backend.fullname" . }}

