apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "places-backend.fullname" . }}
  labels:
    {{- include "places-backend.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: pcasselkv1
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.userAssignedIdentityID }}
    tenantId: b2748d0a-856e-4184-bda8-831f9ffa8a48
    objects: |
      array:
        - |
          objectName: POSTGRESPASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: POSTGRESUSER
          objectType: secret
          objectVersion: ""
  secretObjects:
    - data:
        - key: POSTGRESPASSWORD
          objectName: POSTGRESPASSWORD
        - key: POSTGRESUSER
          objectName: POSTGRESUSER
      secretName: postgres
      type: Opaque

