apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "places-frontend.fullname" . }}
  labels:
    {{- include "places-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "places-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "places-frontend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: pcasselacr.azurecr.io/locations-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http