name: build

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        working-directory: backend
      - run: cargo build --verbose
        working-directory: backend
      - run: cargo test --verbose
        working-directory: backend