name: deploy

on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    name: build and deploy backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        working-directory: backend
      - run: cargo build --verbose
        working-directory: backend
      - run: cargo test --verbose
        working-directory: backend
      - run: cargo build --release --verbose
        working-directory: backend
      - uses: docker/build-push-action@v5
        with:
          context: backend
